steps:
  # Step 1: Build the Docker image
  - name: 'python:3.9-slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install gradio
        python main.py

# Optional: You can define the timeout for the build to make sure it does not exceed the expected time.
timeout: '1200s'  # This sets the timeout to 20 minutes

# You can also specify images to be pushed to Google Container Registry or Artifact Registry
images:
  - 'gcr.io/$PROJECT_ID/my-python-app'
  options:
  logging: CLOUD_LOGGING_ONLY

