steps:
  - name: 'python:3.9-slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install gradio
        python main.py

# Define the timeout for the build
timeout: '1200s'  # This sets the timeout to 20 minutes

# Specify images to be pushed to Google Container Registry or Artifact Registry
images:
  - 'gcr.io/$PROJECT_ID/my-python-app'

# Configuration options for the build
options:
  logging: CLOUD_LOGGING_ONLY
